default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: learning_development
  username: ali
  password: shah
  host: localhost

test:
  <<: *default
  database: learning_test
  username: ali
  password: shah
  host: localhost

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
